/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author amrr
 */
import javax.swing.JOptionPane;
import java.util.List;      // Import the List interface
public class Salary extends javax.swing.JFrame {
    private EmployeeManager employeeManager; // Declare EmployeeManager as a class variable

    /**
     * Creates new form Salary
     */
    public Salary() {
        employeeManager = EmployeeManager.getInstance(); // Get the Singleton instance

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Employee_ID_Field = new javax.swing.JTextField();
        Get_Old_Salary = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        New_Salary_Field = new javax.swing.JTextField();
        Update_Salary = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Deductions_Field = new javax.swing.JTextField();
        Bonus_Field = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("FreeSans", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Payroll System");

        jButton1.setText("previous page");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 550, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(24, 24, 24))
        );

        jLabel2.setFont(new java.awt.Font("FreeSans", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 255));
        jLabel2.setText("Salary");

        jLabel3.setText("Enter ID");

        Employee_ID_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Employee_ID_FieldActionPerformed(evt);
            }
        });

        Get_Old_Salary.setText("get salary");
        Get_Old_Salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Get_Old_SalaryActionPerformed(evt);
            }
        });

        jLabel5.setText("New Salary");

        New_Salary_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                New_Salary_FieldActionPerformed(evt);
            }
        });

        Update_Salary.setText("Update Salary");
        Update_Salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_SalaryActionPerformed(evt);
            }
        });

        jLabel4.setText("Bonus");

        jLabel6.setText("Deductions");

        Deductions_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Deductions_FieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(Update_Salary, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(51, 51, 51)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Employee_ID_Field, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                    .addComponent(New_Salary_Field, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Deductions_Field, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Bonus_Field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(Get_Old_Salary, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Employee_ID_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(Get_Old_Salary, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(New_Salary_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Deductions_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(Bonus_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(117, 117, 117)
                .addComponent(Update_Salary, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //"previous page" button to return to the main page
        main_page main_page = new main_page();
        main_page.show();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Employee_ID_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Employee_ID_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Employee_ID_FieldActionPerformed

    private void New_Salary_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_New_Salary_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_New_Salary_FieldActionPerformed

    private void Get_Old_SalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Get_Old_SalaryActionPerformed
    String employeeID = Employee_ID_Field.getText().trim(); // Get employee ID and trim whitespace

    // Check if employee ID is empty
    if (employeeID.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Employee ID cannot be empty.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
        return; // Exit if validation fails
    }

    // Get the instance of EmployeeManager
    EmployeeManager employeeManager = EmployeeManager.getInstance();
    
    // Retrieve the list of employees
    List<Employee> employees = employeeManager.getEmployees(); 

    Employee foundEmployee = null;

    // Search for the employee in the ArrayList
    for (Employee emp : employees) {
        if (emp.getId().equals(employeeID)) { // Assuming getId() method exists in Employee class
            foundEmployee = emp;
            break; // Exit loop once found
        }
    }

    // Check if employee was found and display salary
    if (foundEmployee != null) {
        double salary = foundEmployee.getSalary(); // Assuming getSalary() method exists in Employee class
        JOptionPane.showMessageDialog(this, "The salary for Employee ID " + employeeID + " is: " + salary, "Salary Information", JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(this, "Employee ID not found.", "Not Found", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_Get_Old_SalaryActionPerformed

    private void Update_SalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_SalaryActionPerformed
    String employeeID = Employee_ID_Field.getText().trim(); // Get employee ID and trim whitespace
    String newSalaryStr = New_Salary_Field.getText().trim(); // Get new salary and trim whitespace
    String BonusStr = Bonus_Field.getText().trim(); // Get new Bonus and trim whitespace
    String DeductionsStr = Deductions_Field.getText().trim(); // Get new Deductions and trim whitespace


    // Check if employee ID or new salary is empty
    if (employeeID.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Employee ID cannot be empty.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
        return; // Exit if validation fails
    }

    if (newSalaryStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "New salary cannot be empty.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
        return; // Exit if validation fails
    }

    try {
        double newSalary = Double.parseDouble(newSalaryStr); // Convert new salary to double
        double newBonus = Double.parseDouble(BonusStr);
        double newDeductions = Double.parseDouble(DeductionsStr);


        // Get the instance of EmployeeManager
        EmployeeManager employeeManager = EmployeeManager.getInstance();
        
        // Retrieve the list of employees
        List<Employee> employees = employeeManager.getEmployees(); 

        Employee foundEmployee = null;

        // Search for the employee in the ArrayList
        for (Employee emp : employees) {
            if (emp.getId().equals(employeeID)) { // Assuming getId() method exists in Employee class
                foundEmployee = emp;
                break; // Exit loop once found
            }
        }

        // Check if employee was found and update salary
        if (foundEmployee != null) {
            foundEmployee.setSalary(newSalary, newDeductions, newBonus); // Assuming setSalary() method exists in Employee class
            JOptionPane.showMessageDialog(this, "Salary updated for Employee ID " + employeeID + " to: " + newSalary, "Update Successful", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Employee ID not found.", "Not Found", JOptionPane.ERROR_MESSAGE);
        }

    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Please enter a valid salary.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_Update_SalaryActionPerformed

    private void Deductions_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Deductions_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Deductions_FieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Salary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bonus_Field;
    private javax.swing.JTextField Deductions_Field;
    private javax.swing.JTextField Employee_ID_Field;
    private javax.swing.JButton Get_Old_Salary;
    private javax.swing.JTextField New_Salary_Field;
    private javax.swing.JButton Update_Salary;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
